### ISSUE TITLE
default vertical padding should be same as Overview

### ISSUE THREAD

**Issue by dhalperi** [uwescience/myria-website#4]
See #3 

When I load <myria.cs.washington.edu> or click the Myria logo, there is a lot (70 pixels worth?) of whitespace at the top. When I click "Overview" this goes away.

**Comment by dhalperi** [comment]
Still not quite the same; page visibly jumps when I click between Logo and Overview, just smaller amount.

Did a hard refresh; happens in Chrome and Safari.

**Comment by domoritz** [comment]
Yes, I experimented a bit with paddings and offsets. The problem is that there are three offsets. One is the padding, one is the scrollspy offset and one is the offset that is used when clicking a link. These three cannot be the same and have to be slightly different to make sure the right menu item is selected when the page is loaded initially, when you click a link and when you scroll. Without spending much more time on fixes, I could not figure out how to make the page not jump at all.

**Comment by dhalperi** [comment]
Okay, will leave as enhancement.
